sonata_admin:
    title: "My Dashboard"
    # title_logo: https://www.istockphoto.com/illustrations/tool-kit
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            default: # This is the default group
                label: My Content

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin] 
