sonata_admin:
    title: "My Dashboard"
    # title_logo: https://www.istockphoto.com/illustrations/tool-kit
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            default: # This is the default group
                label: My Content
    templates:
        edit: '@SonataAdmin/CRUD/edit.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin] 
